// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://miazocmpwkglhpkslkuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pYXpvY21wd2tnbGhwa3Nsa3VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTg3NzYsImV4cCI6MjA2OTk5NDc3Nn0.dauTQwcOo3SpwQS80vGuXOGHjWFMP9189WVMqyIeSOU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});